### ISSUE TITLE
OOM issue training on TPUv3-8

### ISSUE THREAD

**Issue by albertqjiang** [Sea-Snell/JAXSeq#2]
Hi,

I'm trying to fine-tune a gpt-j-6B model on a TPU v3-8 instance. I get an OOM error despite doing model parallelism. Could you please let me know what could be wrong and what possible fixes I can use?

Here's the command I used:
`python examples/gptj_train.py $expname EleutherAI/gpt-j-6B /home/qj213/data/debug.json --use-wandb --wandb-project $expname --model-p-shape 8 --data-p-shape 1 --train-bsize 1 --inference-bsize 1`

And here's the error I received:

> Traceback (most recent call last):
>   File "/home/qj213/JAXSeq/examples/gptj_train.py", line 265, in <module>
>     tyro.cli(main)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/tyro/_cli.py", line 114, in cli
>     _cli_impl(
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/tyro/_cli.py", line 293, in _cli_impl
>     out, consumed_keywords = _calling.call_from_args(
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/tyro/_calling.py", line 192, in call_from_args
>     return unwrapped_f(*args, **kwargs), consumed_keywords  # type: ignore
>   File "/home/qj213/JAXSeq/examples/gptj_train.py", line 239, in main
>     trainer, inference = train_loop(
>   File "/home/qj213/JAXSeq/src/seq2seq_train.py", line 108, in train_loop
>     _, info, trainer = trainer.train_step(items, new_rng)
>   File "/home/qj213/JAXSeq/src/core.py", line 59, in train_step
>     loss, info, new_params, new_optim_state = self.train_fn(self.params, self.optim_state, rng_key, batch)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/experimental/pjit.py", line 138, in wrapped
>     return _python_pjit_helper(infer_params, *args, **kwargs)[0]
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/experimental/pjit.py", line 130, in _python_pjit_helper
>     out_flat = pjit_p.bind(*args_flat, **params)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/core.py", line 328, in bind
>     return self.bind_with_trace(find_top_trace(args), args, params)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/core.py", line 331, in bind_with_trace
>     out = trace.process_primitive(self, map(trace.full_raise, args), params)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/core.py", line 698, in process_primitive
>     return primitive.impl(*tracers, **params)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/experimental/pjit.py", line 919, in _pjit_call_impl
>     compiled = _pjit_lower(
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 3072, in compile
>     self._executable = MeshExecutable.from_hlo(
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 3251, in from_hlo
>     xla_executable = dispatch.compile_or_get_cached(
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/_src/dispatch.py", line 1056, in compile_or_get_cached
>     return backend_compile(backend, serialized_computation, compile_options,
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/_src/profiler.py", line 313, in wrapper
>     return func(*args, **kwargs)
>   File "/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/jax/_src/dispatch.py", line 996, in backend_compile
>     return backend.compile(built_c, compile_options=options)
> jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: XLA:TPU compile permanent error. Ran out of memory in memory space hbm. Used 17.28G of 15.48G hbm. Exceeded hbm capacity by 1.80G.
> 
> Total hbm usage >= 17.80G:
>     reserved        530.00M 
>     program           5.78G 
>     arguments        11.51G 
> 
> Output size 11.51G; shares 11.51G with arguments.
> 
> Program hbm requirement 5.78G:
>     global            1.35M
>     scoped            7.52M
>     HLO temp          5.77G (100.0% utilization: Unpadded (5.76G) Padded (5.76G), 0.2% fragmentation (12.13M))
> 
>   Largest program allocations in hbm:
> 
>   1. Size: 128.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/lm_head/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,8192]{1,0:T(8,128)}
>      Unpadded size: 128.00M
>      XLA label: fusion.1349 = fusion(param.521, convert.1432, fusion.116, fusion.341), kind=kOutput, calls=fused_computation.1094
>      Allocation type: HLO temp
>      ==========================
> 
>   2. Size: 128.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/cond/branch_0_fun/mul" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/optax/_src/transform.py" source_line=405
>      Shape: f32[4096,8192]{1,0:T(8,128)}
>      Unpadded size: 128.00M
>      XLA label: fusion.489 = fusion(get-tuple-element.1378, subtract.201, subtract.200, get-tuple-element.1377, ...(+2)), kind=kLoop, calls=fused_computation.234
>      Allocation type: HLO temp
>      ==========================
> 
>   3. Size: 128.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/cond/branch_0_fun/mul" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/optax/_src/transform.py" source_line=405
>      Shape: f32[8192,4096]{1,0:T(8,128)}
>      Unpadded size: 128.00M
>      XLA label: fusion.486 = fusion(get-tuple-element.2510, subtract.201, subtract.200, get-tuple-element.2509, ...(+2)), kind=kLoop, calls=fused_computation.231
>      Allocation type: HLO temp
>      ==========================
> 
>   4. Size: 128.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/add" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/optax/_src/wrappers.py" source_line=327
>      Shape: f32[8192,4096]{1,0:T(8,128)}
>      Unpadded size: 128.00M
>      XLA label: fusion.1348 = fusion(param.1087, fusion.229, convert.1432), kind=kLoop, calls=fused_computation.1093
>      Allocation type: HLO temp
>      ==========================
> 
>   5. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/13/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1399 = fusion(param.637, convert.1432, fusion.281, get-tuple-element.6842), kind=kOutput, calls=fused_computation.1144
>      Allocation type: HLO temp
>      ==========================
> 
>   6. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/13/mlp/fc_out/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1398 = fusion(param.641, convert.1432, fusion.401, fusion.3882), kind=kOutput, calls=fused_computation.1143
>      Allocation type: HLO temp
>      ==========================
> 
>   7. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/12/mlp/fc_out/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1400 = fusion(param.621, convert.1432, fusion.405, fusion.3867), kind=kOutput, calls=fused_computation.1145
>      Allocation type: HLO temp
>      ==========================
> 
>   8. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/12/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1401 = fusion(param.617, convert.1432, fusion.277, get-tuple-element.6840), kind=kOutput, calls=fused_computation.1146
>      Allocation type: HLO temp
>      ==========================
> 
>   9. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/11/mlp/fc_out/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1402 = fusion(param.601, convert.1432, fusion.409, fusion.3852), kind=kOutput, calls=fused_computation.1147
>      Allocation type: HLO temp
>      ==========================
> 
>   10. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/9/mlp/fc_out/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1354 = fusion(param.1081, convert.1432, fusion.417, fusion.3822), kind=kOutput, calls=fused_computation.1099
>      Allocation type: HLO temp
>      ==========================
> 
>   11. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/cond/branch_0_fun/mul" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/optax/_src/transform.py" source_line=405
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.657 = fusion(get-tuple-element.1410, subtract.201, subtract.200, get-tuple-element.1409, ...(+2)), kind=kLoop, calls=fused_computation.402
>      Allocation type: HLO temp
>      ==========================
> 
>   12. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/9/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1355 = fusion(param.1077, convert.1432, fusion.265, get-tuple-element.6886), kind=kOutput, calls=fused_computation.1100
>      Allocation type: HLO temp
>      ==========================
> 
>   13. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/cond/branch_0_fun/mul" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/optax/_src/transform.py" source_line=405
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.654 = fusion(get-tuple-element.1418, subtract.201, subtract.200, get-tuple-element.1417, ...(+2)), kind=kLoop, calls=fused_computation.399
>      Allocation type: HLO temp
>      ==========================
> 
>   14. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/14/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1397 = fusion(param.657, convert.1432, fusion.285, get-tuple-element.6844), kind=kOutput, calls=fused_computation.1142
>      Allocation type: HLO temp
>      ==========================
> 
>   15. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/11/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1403 = fusion(param.597, convert.1432, fusion.273, get-tuple-element.6838), kind=kOutput, calls=fused_computation.1148
>      Allocation type: HLO temp
>      ==========================
> 
>   16. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/14/mlp/fc_out/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1396 = fusion(param.661, convert.1432, fusion.397, fusion.3897), kind=kOutput, calls=fused_computation.1141
>      Allocation type: HLO temp
>      ==========================
> 
>   17. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/10/mlp/fc_out/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[2048,4096]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1404 = fusion(param.581, convert.1432, fusion.413, fusion.3837), kind=kOutput, calls=fused_computation.1149
>      Allocation type: HLO temp
>      ==========================
> 
>   18. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/10/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1405 = fusion(param.577, convert.1432, fusion.269, get-tuple-element.6836), kind=kOutput, calls=fused_computation.1150
>      Allocation type: HLO temp
>      ==========================
> 
>   19. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/transpose(jvp(FlaxGPTJForCausalLMModule))/transformer/h/15/mlp/fc_in/transpose[permutation=(1, 0)]" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/flax/linen/linear.py" source_line=196
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.1395 = fusion(param.677, convert.1432, fusion.289, get-tuple-element.6846), kind=kOutput, calls=fused_computation.1140
>      Allocation type: HLO temp
>      ==========================
> 
>   20. Size: 32.00M
>      Operator: op_name="pjit(step_fn)/jit(main)/cond/branch_0_fun/mul" source_file="/home/qj213/anaconda3/envs/JaxSeq/lib/python3.9/site-packages/optax/_src/transform.py" source_line=405
>      Shape: f32[4096,2048]{1,0:T(8,128)}
>      Unpadded size: 32.00M
>      XLA label: fusion.651 = fusion(get-tuple-element.1450, subtract.201, subtract.200, get-tuple-element.1449, ...(+2)), kind=kLoop, calls=fused_computation.396
>      Allocation type: HLO temp
>      ==========================

I have used the mesh-transformer-jax library before for fine-tuning the 6B model on the same machine, so it should be possible. If you could help with this issue that'll be truly appreciated!

**Comment by albertqjiang** [comment]
It looks like these allocations are using the f32 datatype. I changed them to bf16 manually and managed to train 6B models with a v3-8. Is this expected?

**Comment by Sea-Snell** [comment]
In my testing, I need model parallel axis of 16 to train GPTJ. And generally you don't want to make the parameters bf16 for training (though I think the activations can be bf16, and obviously bf16 is safe for inference).

**Comment by Sea-Snell** [comment]
Oh btw, you should be able to train GPTJ on TPUV3-8 if you use AdaFactor optimizer

**Comment by albertqjiang** [comment]
Ah great! Thanks for letting me know!!!
