### ISSUE TITLE
any plans for LLaMA training example script?

### ISSUE THREAD

**Issue by 152334H** [Sea-Snell/JAXSeq#5]
Or, if there's any other related resources you could point me to😄

**Comment by Sea-Snell** [comment]
Hi, I will be releasing some new stuff soon, that will be a decent improvement over the current library, and will include better support for llama training. I just pushed a script that you can use for now though. I would also point you to [EasyLM](https://github.com/young-geng/EasyLM), another Jax library for training LMs developed by a collaborator of mine. EasyLM also has support for llama training in Jax.
