### ISSUE TITLE
converting checkpoint to hugginface format?

### ISSUE THREAD

**Issue by ildoonet** [Sea-Snell/JAXSeq#6]
is there any way for converting checkpoint for jax to huggingface format?

**Comment by Sea-Snell** [comment]
Hi thanks for the question! Yes, you can do this by first loading the params with pickle and them serializing them to msg-pack format and saving that to a new file.

An example:
```python
import mlxu
import pickle as pkl
import flax

with open('my_params.pkl', 'rb') as fin:
    params = pkl.load(fin)

with mlxu.open_file('my_new_params.msgpack', 'wb') as fout:
    fout.write(flax.serialization.msgpack_serialize(params, in_place=True))
```
