### ISSUE TITLE
Details about the partitioning rules

### ISSUE THREAD

**Issue by gianlucadetommaso** [Sea-Snell/JAXSeq#7]
Hi,
great work! 

I have been looking into the set of [partition rules](https://github.com/Sea-Snell/JAXSeq/blob/bdb3c46c12d56201d8f87408930d76e4ab99c11a/JaxSeq/models/llama/config.py#L132) that you use to parallelize the models.

Would you mind explaining the idea behind these specific partitioning schemes? Is there any particular heuristic that you are following? For example, I have notice that you often invert the "mp" and "fsdp" axis for consecutive layers. Is this to minimize communication costs, or is there any other reason?

Thanks a lot!

**Comment by Sea-Snell** [comment]
Thanks for the question! And sorry, your issue slipped past me and I just noticed it. So apologies for the late reply.

The idea behind the mp axis is to minimize communication. So:
[a] = [a1]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[a2]

where w1 and w2 are each half of the rows of a matrix w each on a separate device, then when we multiply by a vector [x], we will get:
[a][x] = [a1] [x] = [y1]
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[a2] [x] = [y2]
Where the outputs [y1] and [y2] correspond to half of the full activations on each device. Notably we don't have to do any communication here. We would then apply some activation, which is element wise, so this also has no communication.
Then on the second layer, we can split the weight, b, column-wise to get:
[b] = [b1 b2]

multiplying this by y, gives:
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[y1]
[b][y] = [b1 b2][y2] = (b1)(y1) + (b2)(y2)
thus we need to do 1 all-reduce communication at the end of the forward pass. And if you compute the backward pass you will find that there is also 1 all-reduce on the backward pass. So this pattern of making the consecutive layers alternate for mp minimizes communication by giving 1 communication on the forward pass and 1 on the backward pass.
For fsdp, it doesn't matter what axis you place it on, it's the same communication either way, so we just place it on the other axis that isn't being used for mp.
